version: '3'

services:
  backend:
    build: ./app
    command: gunicorn main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000
    ports:
      - '8000:8000'
    restart: always
    env_file:
      - .env.prod
    depends_on:
      db:
        condition: service_healthy
    networks:
      db-back:

  db:
    image: postgres:15-alpine
    volumes:
      - data:/var/lib/postgresql/data
    env_file:
      - .env.database
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}" ]
      interval: 5s
      retries: 15
    networks:
      db-back:

networks:
  db-back:

volumes:
  data: