version: '2.1'

services:
  backend:
    build: ./land_bank
    ports:
      - '8000:8000'
    restart: always
    env_file:
      - backend.prod.env
    depends_on:
      database:
        condition: service_healthy
    networks:
      postgres-backend:
      redis-backend:

  database:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
#    env_file:
#      - database.env
    environment:
      - POSTGRES_DB=land_bank
      - POSTGRES_USER=land_bank_admin
      - POSTGRES_PASSWORD=berry_postgres
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "land_bank_admin", "-d", "land_bank" ]
      interval: 5s
      retries: 10
    networks:
      postgres-backend:

  redis:
    image: redis:7.2.3
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli ping | grep PONG"]
      interval: 5s
      retries: 10
    networks:
      redis-backend:
    depends_on:
      database:
          condition: service_healthy


networks:
  postgres-backend:
  redis-backend:


volumes:
  redis_data:
  postgres_data:
