version: '3'

services:
  backend:
    build: ./land_bank
    ports:
      - '8000:8000'
    restart: always
    env_file:
      - .env.backend.prod
    depends_on:
      database:
        condition: service_healthy
    networks:
      postgres-backend:
      redis-backend:

  database:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.database
    environment:
      - POSTGRES_DB = "${POSTGRES_DB}"
      - POSTGRES_USER = "${POSTGRES_USER}"
      - POSTGRES_PASSWORD = "${POSTGRES_PASSWORD}"
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}" ]
      interval: 5s
      retries: 10
    networks:
      postgres-backend:

  redis:
    image: redis:7.2.3
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli ping | grep PONG"]
      interval: 5s
      retries: 10
    networks:
      redis-backend:
    depends_on:
      database:
          condition: service_healthy


networks:
  postgres-backend:
  redis-backend:


volumes:
  redis_data:
  postgres_data:
