"""empty message

Revision ID: 1c48c8a65101
Revises: 
Create Date: 2023-11-27 21:20:21.538457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c48c8a65101'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('land_bank_department',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('department_name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('department_name')
    )
    op.create_table('land_bank_position',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('position_name', sa.String(length=64), nullable=False),
    sa.Column('is_director_position', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('position_name')
    )
    op.create_table('land_bank_employee',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('hashed_password', sa.String(length=128), nullable=False),
    sa.Column('last_name', sa.String(length=32), nullable=False),
    sa.Column('first_name', sa.String(length=32), nullable=False),
    sa.Column('patronymic', sa.String(length=32), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('s3_avatar_file', sa.String(length=64), nullable=True),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('employee_head_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['land_bank_department.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['employee_head_id'], ['land_bank_employee.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['position_id'], ['land_bank_position.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_land_bank_employee_email'), 'land_bank_employee', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_land_bank_employee_email'), table_name='land_bank_employee')
    op.drop_table('land_bank_employee')
    op.drop_table('land_bank_position')
    op.drop_table('land_bank_department')
    # ### end Alembic commands ###
