"""empty message

Revision ID: aba570fb9950
Revises: 
Create Date: 2023-12-20 13:03:13.004789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aba570fb9950'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('area_stages',
    sa.Column('stage_name', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stage_name')
    )
    op.create_table('area_working_statuses',
    sa.Column('status_name', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('status_name')
    )
    op.create_table('land_bank_department',
    sa.Column('department_name', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('department_name')
    )
    op.create_table('land_bank_position',
    sa.Column('position_name', sa.String(length=64), nullable=False),
    sa.Column('is_director_position', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('position_name')
    )
    op.create_table('permissions',
    sa.Column('permission_name', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('permission_name')
    )
    op.create_table('cadastral_land_area',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('cadastral_number', sa.String(length=32), nullable=False),
    sa.Column('area_category', sa.String(length=64), nullable=False),
    sa.Column('area_square', sa.Double(), nullable=False),
    sa.Column('address', sa.String(length=64), nullable=False),
    sa.Column('search_channel', sa.String(length=32), nullable=False),
    sa.Column('entered_at_base', sa.DateTime(), nullable=False),
    sa.Column('working_status_id', sa.UUID(), nullable=False),
    sa.Column('stage_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['stage_id'], ['area_stages.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['working_status_id'], ['area_working_statuses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('land_bank_employee',
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('hashed_password', sa.String(length=128), nullable=False),
    sa.Column('last_name', sa.String(length=32), nullable=False),
    sa.Column('first_name', sa.String(length=32), nullable=False),
    sa.Column('patronymic', sa.String(length=32), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('s3_avatar_file', sa.String(length=64), nullable=True),
    sa.Column('position_id', sa.UUID(), nullable=True),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('employee_head_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['land_bank_department.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['employee_head_id'], ['land_bank_employee.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['position_id'], ['land_bank_position.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_land_bank_employee_email'), 'land_bank_employee', ['email'], unique=True)
    op.create_table('permission_position',
    sa.Column('position_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['position_id'], ['land_bank_position.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('area_archived_infos',
    sa.Column('archived_at', sa.DateTime(), nullable=False),
    sa.Column('comment', sa.String(length=128), nullable=True),
    sa.Column('land_area_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['land_area_id'], ['cadastral_land_area.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('area_comments',
    sa.Column('comment_text', sa.String(length=128), nullable=False),
    sa.Column('land_area_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['land_bank_employee.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['land_area_id'], ['cadastral_land_area.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('land_area_buildings',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('commissioning_year', sa.String(length=4), nullable=False),
    sa.Column('land_area_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['land_area_id'], ['cadastral_land_area.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('land_area_objects_owners',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('phone_number', sa.String(length=16), nullable=False),
    sa.Column('location', sa.String(length=128), nullable=True),
    sa.Column('land_area_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['land_area_id'], ['cadastral_land_area.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('land_area_tasks',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('executor_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('land_area_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['land_bank_employee.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['executor_id'], ['land_bank_employee.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['land_area_id'], ['cadastral_land_area.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('land_area_tasks')
    op.drop_table('land_area_objects_owners')
    op.drop_table('land_area_buildings')
    op.drop_table('area_comments')
    op.drop_table('area_archived_infos')
    op.drop_table('permission_position')
    op.drop_index(op.f('ix_land_bank_employee_email'), table_name='land_bank_employee')
    op.drop_table('land_bank_employee')
    op.drop_table('cadastral_land_area')
    op.drop_table('permissions')
    op.drop_table('land_bank_position')
    op.drop_table('land_bank_department')
    op.drop_table('area_working_statuses')
    op.drop_table('area_stages')
    # ### end Alembic commands ###
